import { DataItem } from './ReadingSections';

export const tableData: DataItem[] = [
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },

  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7c9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },
  {
    id: '3d9e6bcd-bbfd-4b2d-bb72-5a6d7sc9a298d',
    patientName: 'Alice Brown',
    doctorName: 'Dr. White',
    readingType: 'Open',
    reportStatus: 'Open',
    date: 'December 8, 2021',
  },

  {
    id: '6g9h6bcd-bbfd-4b2d-bb72-5a6d7c9a2bb2',
    patientName: 'Dana Gray',
    doctorName: 'Dr. Yellow',
    readingType: 'InProgress',
    reportStatus: 'InProgress',
    date: 'December 11, 2021',
  },
  {
    id: '1b9d6bcd-bbfd-4b2d-bb72-5a6d7c9a296b',
    patientName: 'John Doe',
    doctorName: 'Dr. Smith',
    readingType: 'Abnormal Report',
    reportStatus: 'Complete',
    date: 'December 6, 2021',
  },
  {
    id: '6g9h6bcd-bbfd-4b2d-bb72-5a6d7c9a2bb2',
    patientName: 'Dana Gray',
    doctorName: 'Dr. Yellow',
    readingType: 'InProgress',
    reportStatus: 'InProgress',
    date: 'December 11, 2021',
  },

  {
    id: '2c9d6bcd-bbfd-4b2d-bb72-5a6d7c9a297c',
    patientName: 'Jane Doe',
    doctorName: 'Dr. Jones',
    readingType: 'Normal Report',
    reportStatus: 'Complete',
    date: 'December 7, 2021',
  },
  {
    id: '2c9d6bcd-bbfd-4b2d-bb72-dddd',
    patientName: 'Jane Doe',
    doctorName: 'Dr. Jones',
    readingType: 'Normal Report',
    reportStatus: 'Complete',
    date: 'December 7, 2021',
  },
  {
    id: '5f9g6bcd-bbfd-4b2d-bb72-5a6d7c9a2aa1',
    patientName: 'Charlie Black',
    doctorName: 'Dr. Blue',
    readingType: 'Abnormal Report',
    reportStatus: 'Complete',
    date: 'December 10, 2021',
  },
  {
    id: '4e9f6bcd-bbfd-4b2d-bb72-5a6d7c9a299e',
    patientName: 'Bob White',
    doctorName: 'Dr. Green',
    readingType: 'Normal Report',
    reportStatus: 'Complete',
    date: 'December 9, 2021',
  },
  {
    id: '7h9i6bcd-bbfd-4b2d-bb72-5a6d7c9a2cc3',
    patientName: 'Eliot Stone',
    doctorName: 'Dr. Purple',
    readingType: 'Uninterpretable',
    reportStatus: 'Complete',
    date: 'December 12, 2021',
  },
  {
    id: '8i9j6bcd-bbfd-4b2d-bb72-5a6d7c9a2dd4',
    patientName: 'Fiona Crystal',
    doctorName: 'Dr. Orange',
    readingType: 'Normal Report',
    reportStatus: 'Complete',
    date: 'December 13, 2021',
  },
  {
    id: '9j9k6bcd-bbfd-4b2d-bb72-5a6d7c9a2ee5',
    patientName: 'Gary Sand',
    doctorName: 'Dr. Black',
    readingType: 'Abnormal Report',
    reportStatus: 'Complete',
    date: 'December 14, 2021',
  },
  {
    id: '10k9l6cd-bcfd-4b2d-bb72-5a6d7c9a2ff6',
    patientName: 'Helen Marble',
    doctorName: 'Dr. Grey',
    readingType: 'Uninterpretable',
    reportStatus: 'Complete',
    date: 'December 15, 2021',
  },
];
